#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v20
# autospec commit: f35655a
#
Name     : R-corrplot
Version  : 0.95
Release  : 57
URL      : https://cran.r-project.org/src/contrib/corrplot_0.95.tar.gz
Source0  : https://cran.r-project.org/src/contrib/corrplot_0.95.tar.gz
Summary  : Visualization of a Correlation Matrix
Group    : Development/Tools
License  : GPL-2.0 MIT
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![R-CMD-check](https://github.com/taiyun/corrplot/workflows/R-CMD-check/badge.svg)](https://github.com/taiyun/corrplot/actions)
[![codecov.io](https://codecov.io/github/taiyun/corrplot/coverage.svg?branch=master)](https://app.codecov.io/github/taiyun/corrplot?branch=master)
[![CRAN Status](https://www.r-pkg.org/badges/version/corrplot)](https://cran.r-project.org/package=corrplot)
[![CRAN Downloads](https://cranlogs.r-pkg.org/badges/corrplot)](https://www.r-pkg.org/pkg/corrplot)

%prep
%setup -q -n corrplot
pushd ..
cp -a corrplot buildavx2
popd
pushd ..
cp -a corrplot buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1729089979

%install
export SOURCE_DATE_EPOCH=1729089979
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/corrplot/CITATION
/usr/lib64/R/library/corrplot/DESCRIPTION
/usr/lib64/R/library/corrplot/INDEX
/usr/lib64/R/library/corrplot/LICENSE
/usr/lib64/R/library/corrplot/Meta/Rd.rds
/usr/lib64/R/library/corrplot/Meta/features.rds
/usr/lib64/R/library/corrplot/Meta/hsearch.rds
/usr/lib64/R/library/corrplot/Meta/links.rds
/usr/lib64/R/library/corrplot/Meta/nsInfo.rds
/usr/lib64/R/library/corrplot/Meta/package.rds
/usr/lib64/R/library/corrplot/Meta/vignette.rds
/usr/lib64/R/library/corrplot/NAMESPACE
/usr/lib64/R/library/corrplot/NEWS
/usr/lib64/R/library/corrplot/NEWS.md
/usr/lib64/R/library/corrplot/R/corrplot
/usr/lib64/R/library/corrplot/R/corrplot.rdb
/usr/lib64/R/library/corrplot/R/corrplot.rdx
/usr/lib64/R/library/corrplot/doc/corrplot-intro.R
/usr/lib64/R/library/corrplot/doc/corrplot-intro.Rmd
/usr/lib64/R/library/corrplot/doc/corrplot-intro.html
/usr/lib64/R/library/corrplot/doc/index.html
/usr/lib64/R/library/corrplot/help/AnIndex
/usr/lib64/R/library/corrplot/help/aliases.rds
/usr/lib64/R/library/corrplot/help/corrplot.rdb
/usr/lib64/R/library/corrplot/help/corrplot.rdx
/usr/lib64/R/library/corrplot/help/paths.rds
/usr/lib64/R/library/corrplot/html/00Index.html
/usr/lib64/R/library/corrplot/html/R.css
/usr/lib64/R/library/corrplot/tests/testthat.R
/usr/lib64/R/library/corrplot/tests/testthat/test-colorlegend.R
/usr/lib64/R/library/corrplot/tests/testthat/test-cor-mtest.R
/usr/lib64/R/library/corrplot/tests/testthat/test-corrRect.R
/usr/lib64/R/library/corrplot/tests/testthat/test-corrplot.R
